version: '3.3'

services:
  app:
    image: myspringbootcompose:latest
    build:
      context: .
    ports:
      - 8080:8080
    container_name: app
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
    env_file: ${PWD}/env/app.env

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 8082:5432
    networks:
      - backnet
    container_name: db
    env_file: $[PWD]/env/db.env
    volumes:
      - db_data:/var/lib/pgsql/data:rw

volumes:
  db_data:

networks:
  backnet:
  frontnet: